#server:
#  port: 8080
server:
  port: 8443
  ssl:
    bundle: "web-server-pem"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: api-gateway
  ssl:
    bundle:
      pem:
        web-server-pem:
          keystore:
            certificate: "classpath:api-gateway-web-server.crt"
            private-key: "classpath:api-gateway-web-server-private.key"
            private-key-password: "api-gateway-web-server-private.key"
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order
        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/inventory
        - id: eureka-discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka
          filters:
            - SetPath=/
        - id: eureka-discovery-server-static-resources
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/realms/microservices-tutorial-realm
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
    org.springframework.cloud.gateway.route: TRACE
    org.springframework.cloud.gateway: DEBUG
